#!/usr/bin/env bash
# distros/opensuse.sh — openSUSE Leap Minimal-VM cloud image (KVM)
# NOTE: Leap 16 has no separate update repo — security updates land in
# the OSS repo itself, so patching works from oss alone.
DISTRO_ID=opensuse
FAMILY=suse
SUPPORTED_VERSIONS=("16")

resolve_image() {
    VER="${1:-${SUPPORTED_VERSIONS[0]}}"
    case "$VER" in 16) ;; *) die "unsupported opensuse version '$VER'" ;; esac
    LEAP="${VER}.0"                      # global, used by build_suse_repo
    FILE_NAME="Leap-${LEAP}-Minimal-VM.x86_64-Cloud.qcow2"
    IMG_URL="https://download.opensuse.org/distribution/leap/${LEAP}/appliances/${FILE_NAME}"
    SUMS_URLS=("https://download.opensuse.org/distribution/leap/${LEAP}/appliances/${FILE_NAME}.sha256")
    VER_TAG="$LEAP"
}

# zypper repo file pointing at the private mirror.
# Requires: MIRROR_URL, REPO_DIR (e.g. "opensuse/opensuse"), LEAP (e.g. "16.0")
build_suse_repo() {
    cat <<REPO
# Generated by template-generator — private mirror: ${MIRROR_URL}
[biznetgio-oss]
name=BiznetGio Mirror - Leap ${LEAP} OSS
baseurl=${MIRROR_URL}/${REPO_DIR}/distribution/leap/${LEAP}/repo/oss
enabled=1
gpgcheck=1

[biznetgio-non-oss]
name=BiznetGio Mirror - Leap ${LEAP} Non-OSS
baseurl=${MIRROR_URL}/${REPO_DIR}/distribution/leap/${LEAP}/repo/non-oss
enabled=1
gpgcheck=1
REPO
}

customize_repos() {
    local repo_content
    repo_content=$(build_suse_repo) || return 1
    # Park upstream repo definitions so only the mirror is used
    vc --run-command 'mkdir -p /etc/zypp/repos.d.disabled;
mv /etc/zypp/repos.d/*.repo /etc/zypp/repos.d.disabled/ 2>/dev/null; true'
    vc --write "/etc/zypp/repos.d/biznetgio.repo:${repo_content}"
    vc --run-command 'zypper --gpg-auto-import-keys --non-interactive refresh >/dev/null 2>&1; true'
}

customize_pkgs() {
    vc --run-command 'zypper -n --gpg-auto-import-keys install qemu-guest-agent || exit 1; zypper -n clean'
}

customize_patch() {
    vc --run-command 'zypper -n update "kernel*" "openssh*" && zypper -n clean'
}

customize_full_update() {
    vc --run-command 'zypper -n dup --auto-agree-with-licenses && zypper -n clean'
}
