#!/usr/bin/env bash
# lib/common.sh — shared helpers. Sourced by build.sh, not executed directly.

log()  { printf '\033[1;32m==>\033[0m %s\n' "$*"; }
info() { printf '    \033[0;36m%s\033[0m\n' "$*"; }
warn() { printf '\033[1;33mWARN:\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31mERROR:\033[0m %s\n' "$*" >&2; exit 1; }

require_cmds() {
    local missing=() c
    for c in "$@"; do
        command -v "$c" >/dev/null 2>&1 || missing+=("$c")
    done
    if ((${#missing[@]})); then
        die "missing required tools: ${missing[*]}
Hint (Rocky/Alma/CentOS host): dnf install -y guestfs-tools qemu-img
Hint (Ubuntu/Debian host):     apt install -y libguestfs-tools qemu-utils"
    fi
    return 0
}

# fetch <url> <dest-file>
fetch() {
    local url=$1 dest=$2
    log "downloading $(basename "$dest")"
    curl -fL --retry 3 --retry-delay 3 --connect-timeout 20 \
         -o "$dest" "$url" || die "download failed: $url"
}

# verify_checksum <sums-file> <filename-inside-sums> <local-image>
# Understands both "<hash>  <file>" and "SHA256 (<file>) = <hash>" layouts.
verify_checksum() {
    local sums=$1 fname=$2 img=$3 expected algo
    expected=$(awk -v f="$fname" '
        index($0, "(" f ")") > 0 {
            n = split($0, a, /[ \t]+/)
            for (i = 1; i <= n; i++)
                if (a[i] ~ /^[0-9a-fA-F]{64,128}$/) { print a[i]; exit }
        }
        !found && ($2 == f || $2 == "*" f) { print $1; found = 1 }
    ' "$sums" | head -n1)
    [[ -n "$expected" ]] || die "cannot find hash for '$fname' in $sums"
    algo=sha256sum
    [[ ${#expected} == 128 ]] && algo=sha512sum
    info "verifying checksum (${algo})"
    printf '%s  %s\n' "$expected" "$img" | "$algo" -c --status \
        || die "CHECKSUM MISMATCH for $img"
}

# Accumulate virt-customize arguments (single appliance boot = fast)
vc() { VC_ARGS+=("$@"); }

# Shared yum repo content for RHEL-family guests (biznetgio mirror).
# Requires caller to set: MIRROR_URL, VER, REPO_DIR, GPG_KEY_ID, UPSTREAM_KEY_URL
build_rhel_repo() {
    cat <<REPO
# Generated by template-generator — private mirror: ${MIRROR_URL}
[biznetgio-baseos]
name=BiznetGio Mirror - BaseOS
baseurl=${MIRROR_URL}/${REPO_DIR}/${VER}/BaseOS/x86_64/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/${GPG_KEY_ID}-${VER} ${UPSTREAM_KEY_URL}/${GPG_KEY_ID}-${VER}

[biznetgio-appstream]
name=BiznetGio Mirror - AppStream
baseurl=${MIRROR_URL}/${REPO_DIR}/${VER}/AppStream/x86_64/os/
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/${GPG_KEY_ID}-${VER} ${UPSTREAM_KEY_URL}/${GPG_KEY_ID}-${VER}

[biznetgio-crb]
name=BiznetGio Mirror - CRB
baseurl=${MIRROR_URL}/${REPO_DIR}/${VER}/CRB/x86_64/os/
enabled=0
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/${GPG_KEY_ID}-${VER} ${UPSTREAM_KEY_URL}/${GPG_KEY_ID}-${VER}

[biznetgio-epel]
name=BiznetGio Mirror - EPEL
baseurl=${MIRROR_URL}/epel/${VER}/Everything/x86_64/
enabled=0
gpgcheck=1
gpgkey=${UPSTREAM_KEY_URL}/epel/RPM-GPG-KEY-EPEL-${VER}
REPO
}
